name: Cypress

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    environment: env

    steps:
      - uses: actions/checkout@v4

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Instal dependencies
        run: npm ci

      - name: Check API connectivity
        env:
          VITE_API_URL: ${{ vars.VITE_API_URL }}
        run: curl -I $VITE_API_URL

      - name: Build and test project
        uses: cypress-io/github-action@v6
        with:
          build: npm run build
          start: npm run preview
          wait-on: 'http://localhost:4173'
          wait-on-timeout: 120
        env:
          CYPRESS_baseUrl: http://localhost:4173
          VITE_API_URL: ${{ vars.VITE_API_URL }}

      - name: Upload Cypress screenshots
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          if-no-files-found: ignore

      - name: Upload Cypress videos
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: cypress/wideos
          if-no-files-found: ignore