name: Cypress

on:
  push:
    branches: [main]
  pull_request:

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: cypress-io/github-action@v6
        with:
          #build: npm run build
          start: npm run dev
          wait-on: 'http://localhost:4173'
          wait-on-timeout: 120
        env:
          CYPRESS_baseUrl: http://localhost:4173