name: Cypress

on:
  push:
    branches: [main]
  pull_request:

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    environment: env

    steps:
      - uses: actions/checkout@v4

      - name: Check API connectivity
        run: curl -I $VITE_API_URL

      - uses: cypress-io/github-action@v6
        with:
          build: npm run build
          start: npm run preview
          wait-on: 'http://localhost:4173'
          wait-on-timeout: 120
        env:
          CYPRESS_baseUrl: http://localhost:4173